module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    // "./components/Avatar/**/*.{js,ts,jsx,tsx}",
    // "./components/Badge/**/*.{js,ts,jsx,tsx}",
    // "./components/Banner/**/*.{js,ts,jsx,tsx}",
    // "./components/Breadcrumb/**/*.{js,ts,jsx,tsx}",
    // "./components/Buttons/**/*.{js,ts,jsx,tsx}",
    // "./components/Cards/**/*.{js,ts,jsx,tsx}",
    // "./components/ExploreCreators/**/*.{js,ts,jsx,tsx}",
    // "./components/Inputs/**/*.{js,ts,jsx,tsx}",
    // "./components/Navbar/**/*.{js,ts,jsx,tsx}",
    // "./components/Profile/**/*.{js,ts,jsx,tsx}",
    // "./components/Sidebar/**/*.{js,ts,jsx,tsx}",
    // "./components/StakeBanner/**/*.{js,ts,jsx,tsx}",
    // "./components/StakingData/**/*.{js,ts,jsx,tsx}",
    // "./components/Switch/**/*.{js,ts,jsx,tsx}",
    // "./components/Table/**/*.{js,ts,jsx,tsx}",
    // "./components/Tabs/**/*.{js,ts,jsx,tsx}",
    // "./components/Timer/**/*.{js,ts,jsx,tsx}",
    // "./components/TopCollections/**/*.{js,ts,jsx,tsx}",
    // "./components/TopCreators/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'blue-crayola': '#0078FF',
        'outrageous-orange': '#FF6F48',
        'raisin-black': '#2A2938',
        'white': '#FFFFFF',
        'mountain-meadow': '#10B981',
        'mustard': '#FFD748',
        'flame': '#EC522A',
        'medium-slate-blue': '#8B5CF6',
        'maximum-blue': '#3BBEDB',
        'orange': '#FF8719',
        'darker-raisin-black': '#16161D',
        'dark-raisin-black': '#21212C',
        'space-cadet': '#353446',
        'independence': '#403F55',
        'light-independence': '#4B4A64',
        'matte-independence': '#565572',
        'dark-blue-grey': '#625F81',
        'lighter-blue-grey': '#6D6A90',
        'rhythm': '#7B789B',
        'cool-grey': '#8987A6',
        'light-cool-grey': '#9795B1',
        'manatee': '#A6A4BC',
        'lavender-grey': '#B5B3C7',
        'light-lavender-grey': '#C3C1D1',
        'lighter-lavender-grey': '#D1D0DC',
        'gainsboro': '#E0DFE7',
        'ghost-white': '#E8E8EE',
        'fade-ghost-white': '#F1F0F4',
        'cultured': '#F9F9FB',
        'spanish-viridian': '#047857',
        'green-cyan': '#06976A',
        'carribean-green': '#34D399',
        'medium-aquamarine': '#6EE7B7',
        'magic-mint': '#A7F3D0',
        'aero-blue': '#D1FAE5',
        'deep-saffron': '#FF9533',
        'bright-yellow-crayola': '#FFAF37',
        'orange-yellow-crayola': '#FFD75C',
        'jasmine': '#FFE486',
        'blond': '#FFF1C0',
        'cosmic-latte': '#FFFBEC',
        'chinese-red': '#B23E1F',
        'sinopia': '#CC4724',
        'outrageous-red': '#FF714D',
        'vivid-tangerine': '#FF9A80',
        'melon': '#FFC2B2',
        'misty-rose': '#FFEBE5',
        'han-purple': '#6D28D9',
        'blue-violet': '#7C3AED',
        'lavender-floral': '#A78BFA',
        'maximum-blue-purple': '#C4B5FD',
        'lavender-blue': '#D6CDFE',
        'lavender-web': '#EDE9FE',
        'chocolate-traditional': '#803D00',
        'alloy-orange': '#CC6200',
        'rajah': '#FFA24C',
        'mellow-apricot': '#FFBD80',
        'peach-puff': '#FFD7B3',
        'linen': '#FFF2E5',
        'metallic-seaweed': '#198097',
        'pacific-blue': '#289FB9',
        'sky-blue-crayola': '#55E0FF',
        'light-sky-blue-crayola': '#88E9FF',
        'blizzard-blue': '#BBF2FF',
        'azure': '#E5FBFF',
        'rich-chinese-red': '#A63D21',
        'vermilion': '#CC5231',
        'coral': '#FF8766',
        'play-dough': '#FFAF99',
        'unbleached-silk': '#FFD7CC',
        'pale-rose': '#FFEBE5',
        'dark-cornflower-blue': '#003C80',
        'sapphire': '#0054B2',
        'little-boy-blue': '#4CA0FF',
        'french-sky-blue': '#80BBFF',
        'baby-blue-eyes': '#B3D6FF',
        'alice-blue': '#E5F1FF',
        'separator': '#e5e5e5'
      },
      width: {
        '78': '312px',
      }
    },
    fontSize: {
      h1: ['64px', '80.32px'],
      h2: ['48px', '60.24px'],
      h3: ['36px', '45.18px'],
      h4: ['24px', '30.12px'],
      h5: ['18px', '22.59px'],
      h6: ['16px', '20.08px'],
      paragraph: ['16px', '24px'],
      paragraphAlt: ['10px', '12px'],
      smallText: ['12px', '16px'],
      smallSemiBold: ['12px', '20px'],
      semiBold: ['14px', '20px'],
    }
  },
  variants: {},
  plugins: []
};
